version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sua_app
    ports:
      - "4002:4002"
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:latest
    container_name: postgree
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./certs:/certs
    restart: always
    networks:
      - default
