version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgree
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./certs:/certs
    restart: always
networks:
  default:
    driver: bridge
